version: "3.9"

services:
  streamlit:
    build: .
    container_name: streamlit-app
    volumes:
      - .:/app
    ports:
      - "8502:8502"
    stdin_open: true
    tty: true
    restart: unless-stopped
